<a href="https://colab.research.google.com/github/bakeunbi99/Colab/blob/main/Ch1.%ED%8C%8C%EC%9D%B4%EC%8D%AC%20%EB%8D%B0%EC%9D%B4%EB%B6%84%EC%84%9D%20%EA%B8%B0%EC%B4%88/2_Numpy_%EC%8B%A4%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
"""
날짜 : 2021/10/18 15:07
내용 : 파이썬 Numpy 패키지 실습하기

Numpy 라이브러리
  - 고성능의 수치계산을 위한 파이썬 라이브러리
  - 파이썬의 기본 리스트보다 월등한 연산 성능
  - 행렬이나 대규모 다차원 배열 처리를 지원
"""

import numpy as np

In [ ]:
# numpy 벡터
v1 = np.array([1, 2, 3, 4, 5]) # numpy의 리스트
print('v1 : ', v1)

v2 = np.arange(5)
print('v2 : ', v2)

v3 = np.arange(10)
print('v3 : ', v3)

v1 :  [1 2 3 4 5]
v2 :  [0 1 2 3 4]
v3 :  [0 1 2 3 4 5 6 7 8 9]


In [ ]:
# 0 - 1 사이의 임의의 실수 100개
result1 = np.random.rand(100)

# 표준정규분포를 따르는 실수 100개
result2 = np.random.rand(100)

# 0 ~ 9 사이의 임의의 정수
result3 = np.random.rand(10)

In [ ]:
result1, result2, result3 # 전부 벡터 값

(array([0.78534269, 0.57099402, 0.74275681, 0.2809228 , 0.81527883,
        0.48022996, 0.07603445, 0.27331379, 0.46980588, 0.61002969,
        0.48884967, 0.84388834, 0.22725171, 0.18662857, 0.29619661,
        0.77047116, 0.87257668, 0.69685743, 0.41135433, 0.68325578,
        0.65357121, 0.6881414 , 0.84725961, 0.04980828, 0.6740776 ,
        0.3890543 , 0.64694605, 0.03824117, 0.68584899, 0.71851951,
        0.29809788, 0.28212425, 0.49898927, 0.29566208, 0.0508389 ,
        0.91628177, 0.2920507 , 0.03348029, 0.31577596, 0.94071862,
        0.44409716, 0.80466295, 0.83565831, 0.25772568, 0.68731034,
        0.66242985, 0.24740216, 0.52223746, 0.68714444, 0.85745881,
        0.55464994, 0.84915611, 0.26120055, 0.38803294, 0.28862845,
        0.39130734, 0.57796664, 0.10259746, 0.68956035, 0.16716566,
        0.39780806, 0.03304412, 0.92068259, 0.97031636, 0.53066899,
        0.9937282 , 0.86207657, 0.45011972, 0.73648988, 0.1626271 ,
        0.32062143, 0.41318031, 0.9930993 , 0.10

In [ ]:
# numpy 행렬 (2차원 벡터)
m1 = np.array([[1, 2], [3, 4]])
print(m1)

m2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(m2)

m3 = np.ones([2, 4])
print(m3)

m4 = np.zeros([3, 2])
print(m4)



[[1 2]
 [3 4]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
# 행렬 인덱싱 (중요) - [추출]
mat = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(mat)

print(mat[0, 0]) # 0행 0열
print(mat[0, :]) # 1행, 모든 열
print(mat[:, 0]) # 모든행, 0열

print(mat[0:2, 0:2]) # 0행 2행, 0열 2열까지
print(mat[:, 0:2]) # 모든 행에서 0~2까지
print(mat[:, 2:4]) # 모든 행에서 2~4열까지
print(mat[1:3, 1:3]) # 


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1
[1 2 3 4]
[1 5 9]
[[1 2]
 [5 6]]
[[ 1  2]
 [ 5  6]
 [ 9 10]]
[[ 1  2]
 [ 5  6]
 [ 9 10]]
[[ 6  7]
 [10 11]]
